# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.5.2/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.5.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tommaso/DEV/dojo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tommaso/DEV/dojo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.5.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.5.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tommaso/DEV/dojo/CMakeFiles /Users/tommaso/DEV/dojo/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tommaso/DEV/dojo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named clean_cotire

# Build rule for target.
clean_cotire: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clean_cotire
.PHONY : clean_cotire

# fast build rule for target.
clean_cotire/fast:
	$(MAKE) -f CMakeFiles/clean_cotire.dir/build.make CMakeFiles/clean_cotire.dir/build
.PHONY : clean_cotire/fast

#=============================================================================
# Target rules for targets named all_pch

# Build rule for target.
all_pch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 all_pch
.PHONY : all_pch

# fast build rule for target.
all_pch/fast:
	$(MAKE) -f CMakeFiles/all_pch.dir/build.make CMakeFiles/all_pch.dir/build
.PHONY : all_pch/fast

#=============================================================================
# Target rules for targets named Dojo_pch

# Build rule for target.
Dojo_pch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Dojo_pch
.PHONY : Dojo_pch

# fast build rule for target.
Dojo_pch/fast:
	$(MAKE) -f CMakeFiles/Dojo_pch.dir/build.make CMakeFiles/Dojo_pch.dir/build
.PHONY : Dojo_pch/fast

#=============================================================================
# Target rules for targets named Dojo

# Build rule for target.
Dojo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Dojo
.PHONY : Dojo

# fast build rule for target.
Dojo/fast:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/build
.PHONY : Dojo/fast

src/AStar.o: src/AStar.cpp.o

.PHONY : src/AStar.o

# target to build an object file
src/AStar.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/AStar.cpp.o
.PHONY : src/AStar.cpp.o

src/AStar.i: src/AStar.cpp.i

.PHONY : src/AStar.i

# target to preprocess a source file
src/AStar.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/AStar.cpp.i
.PHONY : src/AStar.cpp.i

src/AStar.s: src/AStar.cpp.s

.PHONY : src/AStar.s

# target to generate assembly for a file
src/AStar.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/AStar.cpp.s
.PHONY : src/AStar.cpp.s

src/AnimatedQuad.o: src/AnimatedQuad.cpp.o

.PHONY : src/AnimatedQuad.o

# target to build an object file
src/AnimatedQuad.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/AnimatedQuad.cpp.o
.PHONY : src/AnimatedQuad.cpp.o

src/AnimatedQuad.i: src/AnimatedQuad.cpp.i

.PHONY : src/AnimatedQuad.i

# target to preprocess a source file
src/AnimatedQuad.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/AnimatedQuad.cpp.i
.PHONY : src/AnimatedQuad.cpp.i

src/AnimatedQuad.s: src/AnimatedQuad.cpp.s

.PHONY : src/AnimatedQuad.s

# target to generate assembly for a file
src/AnimatedQuad.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/AnimatedQuad.cpp.s
.PHONY : src/AnimatedQuad.cpp.s

src/BackgroundWorker.o: src/BackgroundWorker.cpp.o

.PHONY : src/BackgroundWorker.o

# target to build an object file
src/BackgroundWorker.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/BackgroundWorker.cpp.o
.PHONY : src/BackgroundWorker.cpp.o

src/BackgroundWorker.i: src/BackgroundWorker.cpp.i

.PHONY : src/BackgroundWorker.i

# target to preprocess a source file
src/BackgroundWorker.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/BackgroundWorker.cpp.i
.PHONY : src/BackgroundWorker.cpp.i

src/BackgroundWorker.s: src/BackgroundWorker.cpp.s

.PHONY : src/BackgroundWorker.s

# target to generate assembly for a file
src/BackgroundWorker.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/BackgroundWorker.cpp.s
.PHONY : src/BackgroundWorker.cpp.s

src/Base64.o: src/Base64.cpp.o

.PHONY : src/Base64.o

# target to build an object file
src/Base64.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Base64.cpp.o
.PHONY : src/Base64.cpp.o

src/Base64.i: src/Base64.cpp.i

.PHONY : src/Base64.i

# target to preprocess a source file
src/Base64.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Base64.cpp.i
.PHONY : src/Base64.cpp.i

src/Base64.s: src/Base64.cpp.s

.PHONY : src/Base64.s

# target to generate assembly for a file
src/Base64.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Base64.cpp.s
.PHONY : src/Base64.cpp.s

src/Color.o: src/Color.cpp.o

.PHONY : src/Color.o

# target to build an object file
src/Color.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Color.cpp.o
.PHONY : src/Color.cpp.o

src/Color.i: src/Color.cpp.i

.PHONY : src/Color.i

# target to preprocess a source file
src/Color.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Color.cpp.i
.PHONY : src/Color.cpp.i

src/Color.s: src/Color.cpp.s

.PHONY : src/Color.s

# target to generate assembly for a file
src/Color.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Color.cpp.s
.PHONY : src/Color.cpp.s

src/DebugUtils.o: src/DebugUtils.cpp.o

.PHONY : src/DebugUtils.o

# target to build an object file
src/DebugUtils.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/DebugUtils.cpp.o
.PHONY : src/DebugUtils.cpp.o

src/DebugUtils.i: src/DebugUtils.cpp.i

.PHONY : src/DebugUtils.i

# target to preprocess a source file
src/DebugUtils.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/DebugUtils.cpp.i
.PHONY : src/DebugUtils.cpp.i

src/DebugUtils.s: src/DebugUtils.cpp.s

.PHONY : src/DebugUtils.s

# target to generate assembly for a file
src/DebugUtils.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/DebugUtils.cpp.s
.PHONY : src/DebugUtils.cpp.s

src/Font.o: src/Font.cpp.o

.PHONY : src/Font.o

# target to build an object file
src/Font.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Font.cpp.o
.PHONY : src/Font.cpp.o

src/Font.i: src/Font.cpp.i

.PHONY : src/Font.i

# target to preprocess a source file
src/Font.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Font.cpp.i
.PHONY : src/Font.cpp.i

src/Font.s: src/Font.cpp.s

.PHONY : src/Font.s

# target to generate assembly for a file
src/Font.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Font.cpp.s
.PHONY : src/Font.cpp.s

src/FrameSet.o: src/FrameSet.cpp.o

.PHONY : src/FrameSet.o

# target to build an object file
src/FrameSet.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/FrameSet.cpp.o
.PHONY : src/FrameSet.cpp.o

src/FrameSet.i: src/FrameSet.cpp.i

.PHONY : src/FrameSet.i

# target to preprocess a source file
src/FrameSet.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/FrameSet.cpp.i
.PHONY : src/FrameSet.cpp.i

src/FrameSet.s: src/FrameSet.cpp.s

.PHONY : src/FrameSet.s

# target to generate assembly for a file
src/FrameSet.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/FrameSet.cpp.s
.PHONY : src/FrameSet.cpp.s

src/Framebuffer.o: src/Framebuffer.cpp.o

.PHONY : src/Framebuffer.o

# target to build an object file
src/Framebuffer.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Framebuffer.cpp.o
.PHONY : src/Framebuffer.cpp.o

src/Framebuffer.i: src/Framebuffer.cpp.i

.PHONY : src/Framebuffer.i

# target to preprocess a source file
src/Framebuffer.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Framebuffer.cpp.i
.PHONY : src/Framebuffer.cpp.i

src/Framebuffer.s: src/Framebuffer.cpp.s

.PHONY : src/Framebuffer.s

# target to generate assembly for a file
src/Framebuffer.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Framebuffer.cpp.s
.PHONY : src/Framebuffer.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GameState.o: src/GameState.cpp.o

.PHONY : src/GameState.o

# target to build an object file
src/GameState.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/GameState.cpp.o
.PHONY : src/GameState.cpp.o

src/GameState.i: src/GameState.cpp.i

.PHONY : src/GameState.i

# target to preprocess a source file
src/GameState.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/GameState.cpp.i
.PHONY : src/GameState.cpp.i

src/GameState.s: src/GameState.cpp.s

.PHONY : src/GameState.s

# target to generate assembly for a file
src/GameState.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/GameState.cpp.s
.PHONY : src/GameState.cpp.s

src/InputDevice.o: src/InputDevice.cpp.o

.PHONY : src/InputDevice.o

# target to build an object file
src/InputDevice.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/InputDevice.cpp.o
.PHONY : src/InputDevice.cpp.o

src/InputDevice.i: src/InputDevice.cpp.i

.PHONY : src/InputDevice.i

# target to preprocess a source file
src/InputDevice.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/InputDevice.cpp.i
.PHONY : src/InputDevice.cpp.i

src/InputDevice.s: src/InputDevice.cpp.s

.PHONY : src/InputDevice.s

# target to generate assembly for a file
src/InputDevice.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/InputDevice.cpp.s
.PHONY : src/InputDevice.cpp.s

src/InputSystem.o: src/InputSystem.cpp.o

.PHONY : src/InputSystem.o

# target to build an object file
src/InputSystem.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/InputSystem.cpp.o
.PHONY : src/InputSystem.cpp.o

src/InputSystem.i: src/InputSystem.cpp.i

.PHONY : src/InputSystem.i

# target to preprocess a source file
src/InputSystem.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/InputSystem.cpp.i
.PHONY : src/InputSystem.cpp.i

src/InputSystem.s: src/InputSystem.cpp.s

.PHONY : src/InputSystem.s

# target to generate assembly for a file
src/InputSystem.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/InputSystem.cpp.s
.PHONY : src/InputSystem.cpp.s

src/Log.o: src/Log.cpp.o

.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i

.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s

.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/Math.o: src/Math.cpp.o

.PHONY : src/Math.o

# target to build an object file
src/Math.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Math.cpp.o
.PHONY : src/Math.cpp.o

src/Math.i: src/Math.cpp.i

.PHONY : src/Math.i

# target to preprocess a source file
src/Math.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Math.cpp.i
.PHONY : src/Math.cpp.i

src/Math.s: src/Math.cpp.s

.PHONY : src/Math.s

# target to generate assembly for a file
src/Math.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Math.cpp.s
.PHONY : src/Math.cpp.s

src/Mesh.o: src/Mesh.cpp.o

.PHONY : src/Mesh.o

# target to build an object file
src/Mesh.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Mesh.cpp.o
.PHONY : src/Mesh.cpp.o

src/Mesh.i: src/Mesh.cpp.i

.PHONY : src/Mesh.i

# target to preprocess a source file
src/Mesh.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Mesh.cpp.i
.PHONY : src/Mesh.cpp.i

src/Mesh.s: src/Mesh.cpp.s

.PHONY : src/Mesh.s

# target to generate assembly for a file
src/Mesh.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Mesh.cpp.s
.PHONY : src/Mesh.cpp.s

src/Noise.o: src/Noise.cpp.o

.PHONY : src/Noise.o

# target to build an object file
src/Noise.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Noise.cpp.o
.PHONY : src/Noise.cpp.o

src/Noise.i: src/Noise.cpp.i

.PHONY : src/Noise.i

# target to preprocess a source file
src/Noise.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Noise.cpp.i
.PHONY : src/Noise.cpp.i

src/Noise.s: src/Noise.cpp.s

.PHONY : src/Noise.s

# target to generate assembly for a file
src/Noise.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Noise.cpp.s
.PHONY : src/Noise.cpp.s

src/Object.o: src/Object.cpp.o

.PHONY : src/Object.o

# target to build an object file
src/Object.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Object.cpp.o
.PHONY : src/Object.cpp.o

src/Object.i: src/Object.cpp.i

.PHONY : src/Object.i

# target to preprocess a source file
src/Object.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Object.cpp.i
.PHONY : src/Object.cpp.i

src/Object.s: src/Object.cpp.s

.PHONY : src/Object.s

# target to generate assembly for a file
src/Object.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Object.cpp.s
.PHONY : src/Object.cpp.s

src/Platform.o: src/Platform.cpp.o

.PHONY : src/Platform.o

# target to build an object file
src/Platform.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Platform.cpp.o
.PHONY : src/Platform.cpp.o

src/Platform.i: src/Platform.cpp.i

.PHONY : src/Platform.i

# target to preprocess a source file
src/Platform.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Platform.cpp.i
.PHONY : src/Platform.cpp.i

src/Platform.s: src/Platform.cpp.s

.PHONY : src/Platform.s

# target to generate assembly for a file
src/Platform.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Platform.cpp.s
.PHONY : src/Platform.cpp.s

src/PolyTextArea.o: src/PolyTextArea.cpp.o

.PHONY : src/PolyTextArea.o

# target to build an object file
src/PolyTextArea.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/PolyTextArea.cpp.o
.PHONY : src/PolyTextArea.cpp.o

src/PolyTextArea.i: src/PolyTextArea.cpp.i

.PHONY : src/PolyTextArea.i

# target to preprocess a source file
src/PolyTextArea.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/PolyTextArea.cpp.i
.PHONY : src/PolyTextArea.cpp.i

src/PolyTextArea.s: src/PolyTextArea.cpp.s

.PHONY : src/PolyTextArea.s

# target to generate assembly for a file
src/PolyTextArea.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/PolyTextArea.cpp.s
.PHONY : src/PolyTextArea.cpp.s

src/Radians.o: src/Radians.cpp.o

.PHONY : src/Radians.o

# target to build an object file
src/Radians.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Radians.cpp.o
.PHONY : src/Radians.cpp.o

src/Radians.i: src/Radians.cpp.i

.PHONY : src/Radians.i

# target to preprocess a source file
src/Radians.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Radians.cpp.i
.PHONY : src/Radians.cpp.i

src/Radians.s: src/Radians.cpp.s

.PHONY : src/Radians.s

# target to generate assembly for a file
src/Radians.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Radians.cpp.s
.PHONY : src/Radians.cpp.s

src/RenderState.o: src/RenderState.cpp.o

.PHONY : src/RenderState.o

# target to build an object file
src/RenderState.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/RenderState.cpp.o
.PHONY : src/RenderState.cpp.o

src/RenderState.i: src/RenderState.cpp.i

.PHONY : src/RenderState.i

# target to preprocess a source file
src/RenderState.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/RenderState.cpp.i
.PHONY : src/RenderState.cpp.i

src/RenderState.s: src/RenderState.cpp.s

.PHONY : src/RenderState.s

# target to generate assembly for a file
src/RenderState.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/RenderState.cpp.s
.PHONY : src/RenderState.cpp.s

src/RenderSurface.o: src/RenderSurface.cpp.o

.PHONY : src/RenderSurface.o

# target to build an object file
src/RenderSurface.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/RenderSurface.cpp.o
.PHONY : src/RenderSurface.cpp.o

src/RenderSurface.i: src/RenderSurface.cpp.i

.PHONY : src/RenderSurface.i

# target to preprocess a source file
src/RenderSurface.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/RenderSurface.cpp.i
.PHONY : src/RenderSurface.cpp.i

src/RenderSurface.s: src/RenderSurface.cpp.s

.PHONY : src/RenderSurface.s

# target to generate assembly for a file
src/RenderSurface.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/RenderSurface.cpp.s
.PHONY : src/RenderSurface.cpp.s

src/Renderable.o: src/Renderable.cpp.o

.PHONY : src/Renderable.o

# target to build an object file
src/Renderable.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Renderable.cpp.o
.PHONY : src/Renderable.cpp.o

src/Renderable.i: src/Renderable.cpp.i

.PHONY : src/Renderable.i

# target to preprocess a source file
src/Renderable.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Renderable.cpp.i
.PHONY : src/Renderable.cpp.i

src/Renderable.s: src/Renderable.cpp.s

.PHONY : src/Renderable.s

# target to generate assembly for a file
src/Renderable.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Renderable.cpp.s
.PHONY : src/Renderable.cpp.s

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/ResourceGroup.o: src/ResourceGroup.cpp.o

.PHONY : src/ResourceGroup.o

# target to build an object file
src/ResourceGroup.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ResourceGroup.cpp.o
.PHONY : src/ResourceGroup.cpp.o

src/ResourceGroup.i: src/ResourceGroup.cpp.i

.PHONY : src/ResourceGroup.i

# target to preprocess a source file
src/ResourceGroup.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ResourceGroup.cpp.i
.PHONY : src/ResourceGroup.cpp.i

src/ResourceGroup.s: src/ResourceGroup.cpp.s

.PHONY : src/ResourceGroup.s

# target to generate assembly for a file
src/ResourceGroup.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ResourceGroup.cpp.s
.PHONY : src/ResourceGroup.cpp.s

src/Semaphore.o: src/Semaphore.cpp.o

.PHONY : src/Semaphore.o

# target to build an object file
src/Semaphore.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Semaphore.cpp.o
.PHONY : src/Semaphore.cpp.o

src/Semaphore.i: src/Semaphore.cpp.i

.PHONY : src/Semaphore.i

# target to preprocess a source file
src/Semaphore.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Semaphore.cpp.i
.PHONY : src/Semaphore.cpp.i

src/Semaphore.s: src/Semaphore.cpp.s

.PHONY : src/Semaphore.s

# target to generate assembly for a file
src/Semaphore.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Semaphore.cpp.s
.PHONY : src/Semaphore.cpp.s

src/Shader.o: src/Shader.cpp.o

.PHONY : src/Shader.o

# target to build an object file
src/Shader.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Shader.cpp.o
.PHONY : src/Shader.cpp.o

src/Shader.i: src/Shader.cpp.i

.PHONY : src/Shader.i

# target to preprocess a source file
src/Shader.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Shader.cpp.i
.PHONY : src/Shader.cpp.i

src/Shader.s: src/Shader.cpp.s

.PHONY : src/Shader.s

# target to generate assembly for a file
src/Shader.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Shader.cpp.s
.PHONY : src/Shader.cpp.s

src/ShaderProgram.o: src/ShaderProgram.cpp.o

.PHONY : src/ShaderProgram.o

# target to build an object file
src/ShaderProgram.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ShaderProgram.cpp.o
.PHONY : src/ShaderProgram.cpp.o

src/ShaderProgram.i: src/ShaderProgram.cpp.i

.PHONY : src/ShaderProgram.i

# target to preprocess a source file
src/ShaderProgram.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ShaderProgram.cpp.i
.PHONY : src/ShaderProgram.cpp.i

src/ShaderProgram.s: src/ShaderProgram.cpp.s

.PHONY : src/ShaderProgram.s

# target to generate assembly for a file
src/ShaderProgram.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ShaderProgram.cpp.s
.PHONY : src/ShaderProgram.cpp.s

src/SoundBuffer.o: src/SoundBuffer.cpp.o

.PHONY : src/SoundBuffer.o

# target to build an object file
src/SoundBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundBuffer.cpp.o
.PHONY : src/SoundBuffer.cpp.o

src/SoundBuffer.i: src/SoundBuffer.cpp.i

.PHONY : src/SoundBuffer.i

# target to preprocess a source file
src/SoundBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundBuffer.cpp.i
.PHONY : src/SoundBuffer.cpp.i

src/SoundBuffer.s: src/SoundBuffer.cpp.s

.PHONY : src/SoundBuffer.s

# target to generate assembly for a file
src/SoundBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundBuffer.cpp.s
.PHONY : src/SoundBuffer.cpp.s

src/SoundListener.o: src/SoundListener.cpp.o

.PHONY : src/SoundListener.o

# target to build an object file
src/SoundListener.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundListener.cpp.o
.PHONY : src/SoundListener.cpp.o

src/SoundListener.i: src/SoundListener.cpp.i

.PHONY : src/SoundListener.i

# target to preprocess a source file
src/SoundListener.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundListener.cpp.i
.PHONY : src/SoundListener.cpp.i

src/SoundListener.s: src/SoundListener.cpp.s

.PHONY : src/SoundListener.s

# target to generate assembly for a file
src/SoundListener.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundListener.cpp.s
.PHONY : src/SoundListener.cpp.s

src/SoundManager.o: src/SoundManager.cpp.o

.PHONY : src/SoundManager.o

# target to build an object file
src/SoundManager.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundManager.cpp.o
.PHONY : src/SoundManager.cpp.o

src/SoundManager.i: src/SoundManager.cpp.i

.PHONY : src/SoundManager.i

# target to preprocess a source file
src/SoundManager.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundManager.cpp.i
.PHONY : src/SoundManager.cpp.i

src/SoundManager.s: src/SoundManager.cpp.s

.PHONY : src/SoundManager.s

# target to generate assembly for a file
src/SoundManager.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundManager.cpp.s
.PHONY : src/SoundManager.cpp.s

src/SoundSet.o: src/SoundSet.cpp.o

.PHONY : src/SoundSet.o

# target to build an object file
src/SoundSet.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundSet.cpp.o
.PHONY : src/SoundSet.cpp.o

src/SoundSet.i: src/SoundSet.cpp.i

.PHONY : src/SoundSet.i

# target to preprocess a source file
src/SoundSet.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundSet.cpp.i
.PHONY : src/SoundSet.cpp.i

src/SoundSet.s: src/SoundSet.cpp.s

.PHONY : src/SoundSet.s

# target to generate assembly for a file
src/SoundSet.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundSet.cpp.s
.PHONY : src/SoundSet.cpp.s

src/SoundSource.o: src/SoundSource.cpp.o

.PHONY : src/SoundSource.o

# target to build an object file
src/SoundSource.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundSource.cpp.o
.PHONY : src/SoundSource.cpp.o

src/SoundSource.i: src/SoundSource.cpp.i

.PHONY : src/SoundSource.i

# target to preprocess a source file
src/SoundSource.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundSource.cpp.i
.PHONY : src/SoundSource.cpp.i

src/SoundSource.s: src/SoundSource.cpp.s

.PHONY : src/SoundSource.s

# target to generate assembly for a file
src/SoundSource.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/SoundSource.cpp.s
.PHONY : src/SoundSource.cpp.s

src/Sprite.o: src/Sprite.cpp.o

.PHONY : src/Sprite.o

# target to build an object file
src/Sprite.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Sprite.cpp.o
.PHONY : src/Sprite.cpp.o

src/Sprite.i: src/Sprite.cpp.i

.PHONY : src/Sprite.i

# target to preprocess a source file
src/Sprite.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Sprite.cpp.i
.PHONY : src/Sprite.cpp.i

src/Sprite.s: src/Sprite.cpp.s

.PHONY : src/Sprite.s

# target to generate assembly for a file
src/Sprite.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Sprite.cpp.s
.PHONY : src/Sprite.cpp.s

src/StateInterface.o: src/StateInterface.cpp.o

.PHONY : src/StateInterface.o

# target to build an object file
src/StateInterface.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/StateInterface.cpp.o
.PHONY : src/StateInterface.cpp.o

src/StateInterface.i: src/StateInterface.cpp.i

.PHONY : src/StateInterface.i

# target to preprocess a source file
src/StateInterface.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/StateInterface.cpp.i
.PHONY : src/StateInterface.cpp.i

src/StateInterface.s: src/StateInterface.cpp.s

.PHONY : src/StateInterface.s

# target to generate assembly for a file
src/StateInterface.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/StateInterface.cpp.s
.PHONY : src/StateInterface.cpp.s

src/String.o: src/String.cpp.o

.PHONY : src/String.o

# target to build an object file
src/String.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/String.cpp.o
.PHONY : src/String.cpp.o

src/String.i: src/String.cpp.i

.PHONY : src/String.i

# target to preprocess a source file
src/String.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/String.cpp.i
.PHONY : src/String.cpp.i

src/String.s: src/String.cpp.s

.PHONY : src/String.s

# target to generate assembly for a file
src/String.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/String.cpp.s
.PHONY : src/String.cpp.s

src/Table.o: src/Table.cpp.o

.PHONY : src/Table.o

# target to build an object file
src/Table.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Table.cpp.o
.PHONY : src/Table.cpp.o

src/Table.i: src/Table.cpp.i

.PHONY : src/Table.i

# target to preprocess a source file
src/Table.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Table.cpp.i
.PHONY : src/Table.cpp.i

src/Table.s: src/Table.cpp.s

.PHONY : src/Table.s

# target to generate assembly for a file
src/Table.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Table.cpp.s
.PHONY : src/Table.cpp.s

src/Tessellation.o: src/Tessellation.cpp.o

.PHONY : src/Tessellation.o

# target to build an object file
src/Tessellation.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Tessellation.cpp.o
.PHONY : src/Tessellation.cpp.o

src/Tessellation.i: src/Tessellation.cpp.i

.PHONY : src/Tessellation.i

# target to preprocess a source file
src/Tessellation.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Tessellation.cpp.i
.PHONY : src/Tessellation.cpp.i

src/Tessellation.s: src/Tessellation.cpp.s

.PHONY : src/Tessellation.s

# target to generate assembly for a file
src/Tessellation.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Tessellation.cpp.s
.PHONY : src/Tessellation.cpp.s

src/TexFormatInfo.o: src/TexFormatInfo.cpp.o

.PHONY : src/TexFormatInfo.o

# target to build an object file
src/TexFormatInfo.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TexFormatInfo.cpp.o
.PHONY : src/TexFormatInfo.cpp.o

src/TexFormatInfo.i: src/TexFormatInfo.cpp.i

.PHONY : src/TexFormatInfo.i

# target to preprocess a source file
src/TexFormatInfo.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TexFormatInfo.cpp.i
.PHONY : src/TexFormatInfo.cpp.i

src/TexFormatInfo.s: src/TexFormatInfo.cpp.s

.PHONY : src/TexFormatInfo.s

# target to generate assembly for a file
src/TexFormatInfo.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TexFormatInfo.cpp.s
.PHONY : src/TexFormatInfo.cpp.s

src/TextArea.o: src/TextArea.cpp.o

.PHONY : src/TextArea.o

# target to build an object file
src/TextArea.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TextArea.cpp.o
.PHONY : src/TextArea.cpp.o

src/TextArea.i: src/TextArea.cpp.i

.PHONY : src/TextArea.i

# target to preprocess a source file
src/TextArea.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TextArea.cpp.i
.PHONY : src/TextArea.cpp.i

src/TextArea.s: src/TextArea.cpp.s

.PHONY : src/TextArea.s

# target to generate assembly for a file
src/TextArea.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TextArea.cpp.s
.PHONY : src/TextArea.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/Timer.o: src/Timer.cpp.o

.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i

.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s

.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/TouchArea.o: src/TouchArea.cpp.o

.PHONY : src/TouchArea.o

# target to build an object file
src/TouchArea.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TouchArea.cpp.o
.PHONY : src/TouchArea.cpp.o

src/TouchArea.i: src/TouchArea.cpp.i

.PHONY : src/TouchArea.i

# target to preprocess a source file
src/TouchArea.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TouchArea.cpp.i
.PHONY : src/TouchArea.cpp.i

src/TouchArea.s: src/TouchArea.cpp.s

.PHONY : src/TouchArea.s

# target to generate assembly for a file
src/TouchArea.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/TouchArea.cpp.s
.PHONY : src/TouchArea.cpp.s

src/Vector.o: src/Vector.cpp.o

.PHONY : src/Vector.o

# target to build an object file
src/Vector.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Vector.cpp.o
.PHONY : src/Vector.cpp.o

src/Vector.i: src/Vector.cpp.i

.PHONY : src/Vector.i

# target to preprocess a source file
src/Vector.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Vector.cpp.i
.PHONY : src/Vector.cpp.i

src/Vector.s: src/Vector.cpp.s

.PHONY : src/Vector.s

# target to generate assembly for a file
src/Vector.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Vector.cpp.s
.PHONY : src/Vector.cpp.s

src/Viewport.o: src/Viewport.cpp.o

.PHONY : src/Viewport.o

# target to build an object file
src/Viewport.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Viewport.cpp.o
.PHONY : src/Viewport.cpp.o

src/Viewport.i: src/Viewport.cpp.i

.PHONY : src/Viewport.i

# target to preprocess a source file
src/Viewport.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Viewport.cpp.i
.PHONY : src/Viewport.cpp.i

src/Viewport.s: src/Viewport.cpp.s

.PHONY : src/Viewport.s

# target to generate assembly for a file
src/Viewport.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/Viewport.cpp.s
.PHONY : src/Viewport.cpp.s

src/WorkerPool.o: src/WorkerPool.cpp.o

.PHONY : src/WorkerPool.o

# target to build an object file
src/WorkerPool.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/WorkerPool.cpp.o
.PHONY : src/WorkerPool.cpp.o

src/WorkerPool.i: src/WorkerPool.cpp.i

.PHONY : src/WorkerPool.i

# target to preprocess a source file
src/WorkerPool.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/WorkerPool.cpp.i
.PHONY : src/WorkerPool.cpp.i

src/WorkerPool.s: src/WorkerPool.cpp.s

.PHONY : src/WorkerPool.s

# target to generate assembly for a file
src/WorkerPool.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/WorkerPool.cpp.s
.PHONY : src/WorkerPool.cpp.s

src/ZipArchive.o: src/ZipArchive.cpp.o

.PHONY : src/ZipArchive.o

# target to build an object file
src/ZipArchive.cpp.o:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ZipArchive.cpp.o
.PHONY : src/ZipArchive.cpp.o

src/ZipArchive.i: src/ZipArchive.cpp.i

.PHONY : src/ZipArchive.i

# target to preprocess a source file
src/ZipArchive.cpp.i:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ZipArchive.cpp.i
.PHONY : src/ZipArchive.cpp.i

src/ZipArchive.s: src/ZipArchive.cpp.s

.PHONY : src/ZipArchive.s

# target to generate assembly for a file
src/ZipArchive.cpp.s:
	$(MAKE) -f CMakeFiles/Dojo.dir/build.make CMakeFiles/Dojo.dir/src/ZipArchive.cpp.s
.PHONY : src/ZipArchive.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... clean_cotire"
	@echo "... all_pch"
	@echo "... Dojo_pch"
	@echo "... Dojo"
	@echo "... src/AStar.o"
	@echo "... src/AStar.i"
	@echo "... src/AStar.s"
	@echo "... src/AnimatedQuad.o"
	@echo "... src/AnimatedQuad.i"
	@echo "... src/AnimatedQuad.s"
	@echo "... src/BackgroundWorker.o"
	@echo "... src/BackgroundWorker.i"
	@echo "... src/BackgroundWorker.s"
	@echo "... src/Base64.o"
	@echo "... src/Base64.i"
	@echo "... src/Base64.s"
	@echo "... src/Color.o"
	@echo "... src/Color.i"
	@echo "... src/Color.s"
	@echo "... src/DebugUtils.o"
	@echo "... src/DebugUtils.i"
	@echo "... src/DebugUtils.s"
	@echo "... src/Font.o"
	@echo "... src/Font.i"
	@echo "... src/Font.s"
	@echo "... src/FrameSet.o"
	@echo "... src/FrameSet.i"
	@echo "... src/FrameSet.s"
	@echo "... src/Framebuffer.o"
	@echo "... src/Framebuffer.i"
	@echo "... src/Framebuffer.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GameState.o"
	@echo "... src/GameState.i"
	@echo "... src/GameState.s"
	@echo "... src/InputDevice.o"
	@echo "... src/InputDevice.i"
	@echo "... src/InputDevice.s"
	@echo "... src/InputSystem.o"
	@echo "... src/InputSystem.i"
	@echo "... src/InputSystem.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/Math.o"
	@echo "... src/Math.i"
	@echo "... src/Math.s"
	@echo "... src/Mesh.o"
	@echo "... src/Mesh.i"
	@echo "... src/Mesh.s"
	@echo "... src/Noise.o"
	@echo "... src/Noise.i"
	@echo "... src/Noise.s"
	@echo "... src/Object.o"
	@echo "... src/Object.i"
	@echo "... src/Object.s"
	@echo "... src/Platform.o"
	@echo "... src/Platform.i"
	@echo "... src/Platform.s"
	@echo "... src/PolyTextArea.o"
	@echo "... src/PolyTextArea.i"
	@echo "... src/PolyTextArea.s"
	@echo "... src/Radians.o"
	@echo "... src/Radians.i"
	@echo "... src/Radians.s"
	@echo "... src/RenderState.o"
	@echo "... src/RenderState.i"
	@echo "... src/RenderState.s"
	@echo "... src/RenderSurface.o"
	@echo "... src/RenderSurface.i"
	@echo "... src/RenderSurface.s"
	@echo "... src/Renderable.o"
	@echo "... src/Renderable.i"
	@echo "... src/Renderable.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/ResourceGroup.o"
	@echo "... src/ResourceGroup.i"
	@echo "... src/ResourceGroup.s"
	@echo "... src/Semaphore.o"
	@echo "... src/Semaphore.i"
	@echo "... src/Semaphore.s"
	@echo "... src/Shader.o"
	@echo "... src/Shader.i"
	@echo "... src/Shader.s"
	@echo "... src/ShaderProgram.o"
	@echo "... src/ShaderProgram.i"
	@echo "... src/ShaderProgram.s"
	@echo "... src/SoundBuffer.o"
	@echo "... src/SoundBuffer.i"
	@echo "... src/SoundBuffer.s"
	@echo "... src/SoundListener.o"
	@echo "... src/SoundListener.i"
	@echo "... src/SoundListener.s"
	@echo "... src/SoundManager.o"
	@echo "... src/SoundManager.i"
	@echo "... src/SoundManager.s"
	@echo "... src/SoundSet.o"
	@echo "... src/SoundSet.i"
	@echo "... src/SoundSet.s"
	@echo "... src/SoundSource.o"
	@echo "... src/SoundSource.i"
	@echo "... src/SoundSource.s"
	@echo "... src/Sprite.o"
	@echo "... src/Sprite.i"
	@echo "... src/Sprite.s"
	@echo "... src/StateInterface.o"
	@echo "... src/StateInterface.i"
	@echo "... src/StateInterface.s"
	@echo "... src/String.o"
	@echo "... src/String.i"
	@echo "... src/String.s"
	@echo "... src/Table.o"
	@echo "... src/Table.i"
	@echo "... src/Table.s"
	@echo "... src/Tessellation.o"
	@echo "... src/Tessellation.i"
	@echo "... src/Tessellation.s"
	@echo "... src/TexFormatInfo.o"
	@echo "... src/TexFormatInfo.i"
	@echo "... src/TexFormatInfo.s"
	@echo "... src/TextArea.o"
	@echo "... src/TextArea.i"
	@echo "... src/TextArea.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/TouchArea.o"
	@echo "... src/TouchArea.i"
	@echo "... src/TouchArea.s"
	@echo "... src/Vector.o"
	@echo "... src/Vector.i"
	@echo "... src/Vector.s"
	@echo "... src/Viewport.o"
	@echo "... src/Viewport.i"
	@echo "... src/Viewport.s"
	@echo "... src/WorkerPool.o"
	@echo "... src/WorkerPool.i"
	@echo "... src/WorkerPool.s"
	@echo "... src/ZipArchive.o"
	@echo "... src/ZipArchive.i"
	@echo "... src/ZipArchive.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

